version: '2.1'
services:
    postgis:
        build: .
        environment:
            - POSTGRES_PASSWORD=yourpasswordhere
        image: docker.io/znmeb/postgis
        ports: 
        - '5439:5432'
