version: '3.4'
services:
    postgis:
        environment:
            - POSTGRES_PASSWORD=yourpasswordhere
            - PGDATA=/var/lib/postgresql/data/pgdata
        image: docker.io/znmeb/postgis
        ports: 
        - '5439:5432'
        volumes:
        - /data/pgdata:/var/lib/postgresql/data/pgdata
