version: '3.4'
services:
    postgis:
        build:
            context: .
            dockerfile: postgis.Dockerfile
        environment:
            - POSTGRES_PASSWORD=$PGPASSWORD
            - PGDATA=/var/lib/postgresql/data/pgdata
        image: docker.io/znmeb/postgis
        ports: 
        - '5439:5432'
        volumes:
        - /data/gisdata:/gisdata
        - /data/pgdata:/var/lib/postgresql/data/pgdata
