version: '3.4'
services:
    postgis:
        build:
            context: .
            dockerfile: postgis.Dockerfile
        environment:
            - POSTGRES_PASSWORD=yourpasswordhere
        image: docker.io/znmeb/postgis
        ports: 
        - '5439:5432'
        volumes:
        - ./gisdata:/gisdata
