version: '3.4'
services:
    postgis-geocoder:
        build:
            context: .
            dockerfile: postgis-geocoder.Dockerfile
        environment:
            - POSTGRES_PASSWORD=yourpasswordhere
            - PGDATA=/var/lib/postgresql/data/pgdata
        image: docker.io/znmeb/postgis-geocoder
        ports: 
        - '5438:5432'
        - /data/gisdata:/gisdata
        - /data/pgdata:/var/lib/postgresql/data/pgdata
