#! /bin/bash

echo "Adding PostgreSQL / PostGIS package repository"
sudo cp postgis.list /etc/apt/sources.list.d/
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc \
  | sudo apt-key add -
sudo apt-get update
echo "http://apt.postgresql.org/pub/repos/apt repository added!"
echo ""
echo "Installing PostGIS packages"
sudo apt-get install -y \
  postgresql-9.6 \
  postgresql-client-9.6 \
  postgresql-contrib-9.6 \
  postgresql-doc-9.6 \
  postgresql-server-dev-9.6 \
  postgresql-9.6-postgis-2.3 \
  postgresql-9.6-pgrouting \
  postgresql-9.6-pgrouting-doc \
  postgresql-9.6-postgis-2.3-scripts

echo "Creating PostgreSQL superuser ${USER}."
echo "If you're already a PostgreSQL superuser you can ignore the error message."
sudo su -c "createuser -s ${USER}" postgres
echo "You are now a PostgreSQL super-user with ID '${USER}'."
echo "Creating a personal database for ${USER}."
echo "If you've already created the ${USER} database you can ignore the error message."
createdb -O ${USER} ${USER}
echo "Your personal database ${USER} has been created."
echo ""
echo "Creating extensions in your personal database."
echo "If you've already created the extensions you can ignore the error messages."
echo "extension postgis"
psql -c "CREATE EXTENSION postgis CASCADE;"
echo "extension postgis_topology"
psql -c "CREATE EXTENSION postgis_topology CASCADE;"
echo "extension pgrouting"
psql -c "CREATE EXTENSION pgrouting CASCADE;"
echo "extension address_standardizer"
psql -c "CREATE EXTENSION address_standardizer CASCADE;"
echo "extension address_standardizer_data_us"
psql -c "CREATE EXTENSION address_standardizer_data_us CASCADE;"
echo "extension postgis_tiger_geocoder"
psql -c "CREATE EXTENSION postgis_tiger_geocoder CASCADE;"
